Repository filecoin-project/lily, pull requests merged in 2020-12, with the labels that each got.

#249 feat: add watch and walk commands to index chain during traversal
  chain/actor.go
  chain/block.go
  chain/economics.go
  chain/indexer.go
  chain/message.go
  chain/storage.go
  commands/migrate.go
  commands/run.go
  commands/setup.go
  commands/walk.go
  commands/watch.go
  go.mod
  go.sum
  lens/carrepo/carrepo.go
  lens/interface.go
  lens/lotus/api.go
  lens/lotusrepo/repo.go
  lens/sqlrepo/repo.go
  lens/util/repo.go
  main.go
  model/actors/common/task.go
  model/actors/market/task.go
  model/visor/report.go
  storage/migrations/22_visor_processing_reports.go
  storage/sql.go
  tasks/actorstate/actor.go
  tasks/actorstate/actorstate.go
  tasks/actorstate/actorstatechange.go
  tasks/actorstate/init.go
  tasks/actorstate/market.go
  tasks/actorstate/miner.go
  tasks/actorstate/multisig.go
  tasks/actorstate/power.go
  tasks/actorstate/reward.go
  tasks/indexer/chainheadindexer.go
  tasks/indexer/chainheadindexer_test.go
  tasks/indexer/chainhistoryindexer.go
  tasks/indexer/chainhistoryindexer_test.go
  testutil/lens.go
Labels: kind/enhancement

#291 fix(schema): fix primary key for miner_sector_deals table
  model/actors/miner/sectordeals.go
  storage/migrations/23_miner_sector_deals_pk.go
Labels: kind/bug

#281 Run full testing suite in CI with code coverage
  .circleci/config.yml
  .codecov.yml
  Makefile
Labels: kind/chore, kind/test

#270 feat(gas outputs): Add Height and ActorName
  chain/message.go
  model/derived/gasoutputs.go
  storage/migrations/25_gasoutputs_height_code.go
  storage/sql.go
  tasks/message/gasoutputs.go
Labels: kind/enhancement

#304 fix: use migration database connection when installing timescale extension
  storage/migrate.go
Labels: kind/bug

#309 fix: close all processor connections to lotus on fatal error
  chain/indexer.go
Labels: kind/bug

#303 perf: replace local state diffing with StateChangeActors API method
  chain/actor.go
Labels: kind/enhancement

#305 feat: allow finer-grained actor task processing
  chain/actor.go
  chain/indexer.go
  commands/walk.go
  commands/watch.go
Labels: kind/enhancement

#308 chore(api): trim the lens API to required methods
  lens/interface.go
  tasks/actorstate/actorstate.go
Labels: kind/chore

#324 Allow model upsertion
  commands/migrate.go
  commands/setup.go
  go.mod
  go.sum
  main.go
  storage/sql.go
  storage/sql_test.go
Labels: kind/feature
