Repository filecoin-project/lily, pull requests merged in 2020-10, with the labels that each got.

#86 feat(debug): Process actor by head without persistance
  commands/debug.go
  main.go
  storage/sql.go
  tasks/actorstate/actorstate.go
Labels: enhancement

#140 Fix Repo loading of Car files
  go.mod
  go.sum
  lens/carrepo/carrepo.go
  lens/carrepo/proxystore.go
Labels: kind/bug

#139 chore: add issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/new_story.md
Labels: kind/chore

#158 polish: update miner processing logic
  go.mod
  go.sum
  model/actors/miner/currentdeadline.go
  model/actors/miner/feedebt.go
  model/actors/miner/lockedfunds.go
  model/actors/miner/minerinfo.go
  model/actors/miner/power.go
  model/actors/miner/precommit.go
  model/actors/miner/sector.go
  model/actors/miner/sectordeals.go
  model/actors/miner/sectorevents.go
  model/actors/miner/sectorposts.go
  model/actors/miner/state.go
  model/actors/miner/task.go
  model/genesis/task.go
  storage/migrations/15_miner_actor_refactor.go
  storage/sql.go
  tasks/actorstate/genesis.go
  tasks/actorstate/miner.go
Labels: kind/enhancement

#178 feat: allow actor state processor to run without leasing
  commands/debug.go
  commands/run.go
  storage/sql.go
  tasks/actorstate/actorstate.go
Labels: kind/enhancement

#180 open lotusrepo lens read only
  lens/lotusrepo/repo.go
Labels: kind/bug
